# Dependencies
markdown:	kramdown
pygments:	true

# Permalinks
permalink: /:month-:day-:year/:categories/:title

# Setup
title:		craig eley dot com
tagline:	'blog'
description:	'My personal blog.'
# url: http://craigeley.github.io

author:
  name:		'Craig Eley'
  url:		https://craigeley.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/images/pink-radio.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/craigeley
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/craigeley
    desc:	Fork me on github

  - icon:	instagram
    url:	https://instagram.com/craigeley
    desc:	Follow me on Instagram

  - icon:	feed
    url:	http://craigeley.github.io/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Blog
    url:	/#blog
    
  - title:	About
    url:	/about
    
copyright:
  author:	Craig Eley
  url:		http://craigeley.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
