# Site settings
title: craig eley dot com
email: craigeley@gmail.com
description: "The personal online home of Craig Eley, radio producer and researcher"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D66B29
  secondary: D66B29  
  secondary-dark: 333

# Team names, titles and social links

people:
- name: Craig Eley
  pic: 2
  position: The Groom
  social:
    - title: twitter
      url: http://twitter.com/craigeley
    - title: instagram
      url: http://instagram.com/craigeley
    - title: envelope
      url: mailto:craigeley@gmail.com?subject=Website%20Contact


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/craigeley
  - title: instagram
    url: http://instagram.com/craigeley
  - title: github
    url: http://github.com/craigeley
  - title: soundcloud
    url: http://soundcloud.com/craigeley

# Postal address (add as many lines as necessary)
address:
  - line: 821 University Ave.
  - line: Madison, WI 53703

# Build settings
markdown: kramdown
permalink: pretty

# Permalinks
permalink: /:month-:day-:year/:categories/:title/
tag_dir: tagged

gems:
  - jekyll-redirect-from