# Dependencies
markdown: kramdown
highlights: null

# Permalinks
permalink: /:month-:day-:year/:categories/:title

# Setup

title:  craig eley dot com
tagline: 'sound | nature | technology'
description: 'My personal blog.'

url: http://craigeley.github.io

owner:
  name:           Craig Eley
  avatar:         avatar.png
  bio:            "Public Fellow, Radio Producer, Good Listener"
  email:          craig@craigeley.com
  twitter:        craigeley        
  github:         craigeley       
  instagram:      craigeley     
  disqus:         craigeley

author:
  name: 'Craig Eley'
  url: http://craigeley.github.io

paginate: 10

# Custom vars
icon:		/assets/images/icon.png
cover:		/images/pink-radio.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/craigeley
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/craigeley
    desc:	Fork me on github

  - icon:	instagram
    url:	https://instagram.com/craigeley
    desc:	Follow me on Instagram

  - icon:	feed
    url:	http://craigeley.github.io/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Blog
    url:	/#article
    
  - title:	Home
    url:	/
    
copyright:
  author:	Craig Eley
  url:		http://craigeley.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/4.0/
